import type { Metadata } from "next";
import { Teko } from "next/font/google"; // Use a valid font import
import "./globals.css";
import Provider from "./provider";


const teko = Teko({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${teko.className} bg-white dark:bg-black text-black dark:text-white`}
      >
        <Provider>    
        {children}
        </Provider>
        
      </body>
    </html>
  );
}